spring:
  profiles:
    active: local
server:
  port: 8081
topics:
  library-events: library-events
  retry: 'library-events.RETRY'
  dlt: 'library-events.DLT'
---
spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
#    listener:
#      ack-mode: manual
#      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: library-events
