spring:

  application.name: my-library-events-consumer-2
  profiles:
    active: local

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      group-id: library-events-listener-group
      properties:
        spring.deserializer.value.delegate.class:  org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.jskno.my.library.events.consumer2.domain.LibraryEventDTO

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    open-in-view: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

server:
  port: 8081



