
spring:
  kafka:
    bootstrap-servers: pkc-12576z.us-west2.gcp.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='WTHUTRM57A2FQF7S' password='/4YM6KP2v+D5bY3Agio3hTiyy/PlDV72Asd/GeNNETr+NKRPZmfkb9x8fe3yQfn/';
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: kafka-101-spring
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka.purchases.topic: purchases